# Generated by Django 2.0.7 on 2018-12-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogPost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='update_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
