# Generated by Django 2.0.7 on 2018-12-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogPost', '0005_auto_20181222_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='blog/static/images/'),
        ),
    ]
