# Generated by Django 2.0.7 on 2019-01-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogPost', '0009_auto_20190110_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
