# Generated by Django 2.0.7 on 2019-01-11 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogPost', '0014_demo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Demo',
        ),
    ]
