# Generated by Django 2.0.7 on 2019-01-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogPost', '0015_delete_demo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='.'),
        ),
    ]
