# Generated by Django 2.0.7 on 2019-02-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogPost', '0016_auto_20190112_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='default.png', upload_to='.'),
        ),
    ]
